name: BGM-SBJ-SPIDER

# Run every day
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - name: Run Script
      run: |
        npm install
        node update.js
    - name: Commit Updates
      id: commit
      run: |
        git config --local user.email "68130732+hakubotto@users.noreply.github.com"
        git config --local user.name "hakubotto"
        time=$(date "+%Y%m%d%H%M%S")
        git add . -v
        git commit -m "Ver-${time} Updated"
        echo ::set-output name=time::$time
        git push
